#Configuración del entorno (pool) y variables
trigger: none

pool:
  vmImage: 'ubuntu-latest'
  demands: java

variables:
  wrapperScript: 'gradlew'
  tasks: 'clean test jacocoTestReport build'

#Paso 1. Compilación y pruebas con Gradle
steps:
- task: Gradle@3
  displayName: 'gradlew clean test jacocoTestReport build'
  inputs:
    gradleWrapperFile: '$(wrapperScript)'
    tasks: '$(tasks)'
    jdkVersionOption: '17'

#Paso 2. Preparación de SonarCloud
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@4
  displayName: 'Prepare analysis on SonarQube Cloud'
  inputs:
    SonarQube: SonarCloud
    organization: quind
    projectKey: com.entrenamiento.Calculadora
    projectName: 'Calculadora'

#Paso 3. Análisis de Código con SonarCloud
- task: Gradle@3
  displayName: 'Execute sonarqube analysis'
  inputs:
    gradleWrapperFile: '$(wrapperScript)'
    tasks: 'sonarqube'
    jdkVersionOption: '17'

#Paso 4. Publicación de resultados de SonarCloud
- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@4
  displayName: 'Publish Quality Gate Result'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

#Paso 5. Gestión de artefactos: Publicación de los archivos .jar generados
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()